# fly.toml app configuration file generated for pricetracker-back-blue-tree-3177 on 2024-01-15T16:44:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pricetracker-back-blue-tree-3177"
primary_region = "syd"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
